//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommon.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string errGeneral {
            get {
                return ResourceManager.GetString("errGeneral", resourceCulture);
            }
        }
        
        internal static string errInvalidController {
            get {
                return ResourceManager.GetString("errInvalidController", resourceCulture);
            }
        }
        
        internal static string errInvalidToken {
            get {
                return ResourceManager.GetString("errInvalidToken", resourceCulture);
            }
        }
        
        internal static string errItemNotFound {
            get {
                return ResourceManager.GetString("errItemNotFound", resourceCulture);
            }
        }
        
        internal static string errMethodNotImplemented {
            get {
                return ResourceManager.GetString("errMethodNotImplemented", resourceCulture);
            }
        }
        
        internal static string errAccountNotVerified {
            get {
                return ResourceManager.GetString("errAccountNotVerified", resourceCulture);
            }
        }
    }
}
